spring:
  application:
    name: ${SPRING_APP_NAME:products-service}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:4000/auth}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}

  security:
    oauth2:
      authorization:
        oidc:
          client-id: ${OIDC_CLIENT_ID:luxehouseapi}
          client-secret: ${OIDC_CLIENT_SECRET:$2y$10$SbUNTg7IjlTIEZ4Zl20rweq.e7n61F6rdJlmuV2ieGc8Z0UjHOILi} # b-scrypt luxehouseapi

server:
  port: ${SERVER_PORT:9000}

logging:
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    org.springframework.cache: ${SPRING_CACHE_LOG_LEVEL:DEBUG}
    org.springframework.cache.interceptor.CacheInterceptor: ${SPRING_CACHE_LOG_LEVEL:DEBUG}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
