server:
  port: 8888

app:
  api:
    version: v1
    prefix: /api/${app.api.version}
    stripPrefix: 2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
              - Path=${app.api.prefix}/auth/**
          filters:
              - StripPrefix=${app.api.stripPrefix}
        - id: product-service
          uri: http://localhost:8081
          predicates:
              - Path=${app.api.prefix}/products/**
          filters:
              - StripPrefix=${app.api.stripPrefix}

logging:
  level:
    root: INFO
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:DEBUG} # Security logs
    org.springframework.cache: ${SPRING_CACHE_LOG_LEVEL:DEBUG}      # Cache logs
    org.springframework.cache.interceptor.CacheInterceptor: ${CACHE_INTERCEPTOR_LOG_LEVEL:TRACE} # Detailed cache logging
    com.example.application.service: INFO                                         # Application services
    com.example.application.repository: DEBUG                                     # Application repository
    com.example.application.controller: DEBUG                                     # Application controller
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%magenta(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %cyan(%logger{15}) - %msg%n}
