services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

  # Kafka Service
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LOG_DIRS=/kafka/logs
      - KAFKA_PORT=9092
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    volumes:
      - /tmp/broker-metadata:/kafka/broker-metadata
      - /tmp/kafka-logs:/kafka/logs
    ports:
      - "9092:9092"
    networks:
      - my-network

# Volumes for persistent data
volumes:
  mysql_data:
  redis_data:

# Network for all services
networks:
  my-network:
    driver: bridge
