spring:
  application:
    name: ${SPRING_APP_NAME:products-service}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3307/products}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:true}
  web:
    resources:
      add-mappings: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-idle: 20
          min-idle: 2
          max-active: 20
          max-wait: 3000ms

logging:
  level:
    root: INFO
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:DEBUG} # Security logs
    org.springframework.cache: ${SPRING_CACHE_LOG_LEVEL:DEBUG}      # Cache logs
    org.springframework.cache.interceptor.CacheInterceptor: ${CACHE_INTERCEPTOR_LOG_LEVEL:TRACE} # Detailed cache logging
    com.example.application.service: INFO                                         # Application services
    com.example.application.repository: DEBUG                                     # Application repository
    com.example.application.controller: DEBUG                                     # Application controller
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%magenta(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %cyan(%logger{15}) - %msg%n}

server:
  port: ${SERVER_PORT:8081}
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}

jwt:
  rsa-public-key: classpath:certs/publicKey.pem