services:
    python-env:
    image: python:3.10
    container_name: python-env
    restart: always
    volumes:
        - .:/app # Mount local project into the container
    working_dir: /app
    ports:
        - '5000:5000' # Expose Flask API
    command: /bin/bash -c "pip install flask flask-cors mysql-connector-python requests && tail -f /dev/null"
