spring:
    application:
        name: ${SPRING_APP_NAME:eyeglass}
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: ${JPA_SHOW_SQL:true}
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    web:
        resources:
            add-mappings: false

logging:
    level:
        org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    pattern:
        console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

server:
    servlet:
        session:
            timeout: ${SESSION_TIMEOUT:20m}

jwt:
    rsa-private-key: classpath:certs/privateKey.pem
    rsa-public-key: classpath:certs/publicKey.pem

paypal:
    client:
        id: ${PAYPAL_CLIENT_ID}
        secret: ${PAYPAL_CLIENT_SECRET}
    mode: ${PAYPAL_MODE:sandbox}
